# Generated by Django 4.2.7 on 2023-11-09 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for the user account.', primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(help_text='Email address used for user identification.', max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Indicates whether the user has superuser privileges.')),
                ('is_staff', models.BooleanField(default=False, help_text='Indicates whether the user has staff privileges.')),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (0, 'Not Active'), (2, 'Pending')], default=1, help_text='User account status')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Time when the user account was created.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the user account is deleted.')),
                ('deletion_date', models.DateTimeField(blank=True, editable=False, help_text='Time when the user account was deleted', null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
